/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IndexService */

#ifndef _Included_IndexService
#define _Included_IndexService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IndexService
 * Method:    index
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_IndexService_index
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
