/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bg_nbu_java_server_plugin_IndexService */

#ifndef _Included_bg_nbu_java_server_plugin_IndexService
#define _Included_bg_nbu_java_server_plugin_IndexService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bg_nbu_java_server_plugin_IndexService
 * Method:    index
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_bg_nbu_java_server_plugin_IndexService_index
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
